name: object_detection
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy=1.21.2
  - pandas=1.3.2
  - matplotlib=3.4.3
  - opencv=4.5.3
  - pillow=8.3.2
  - tqdm=4.62.3
  - scipy=1.7.1
  - pycocotools=2.0.6
