name: semantic_segmentation
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia

dependencies:
  - python=3.8
  - numpy=1.21
  - matplotlib=3.4
  - pillow=8.2
  - opencv=4.5
  - jupyter=1.0
  - cudatoolkit=11.8  # Ini adalah dependensi CUDA yang sesuai dengan pytorch-cuda=11.8

  # Perintah berikut ini adalah perintah yang Anda ingin tambahkan
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8

  # Library/package dari pip
  - pip:
    - scikit-image==0.18
    - tqdm==4.62
    - tensorboardX==2.4
    - cityscapesscripts==2.2